<?php 
function regpanel_menu() {

$items = array();

$items['regpanel'] = array(
'title' => 'Reg Panel',
'description' => 'A registration panel',
'page callback' => 'drupal_get_form',
'page arguments' => array('regpanel_form'),
'access callback' => TRUE

);

return $items;

}

function regpanel_form($form, &$form_state) {

$form['login'] = array(
'#type' => 'item',
'#title' => t(''),
'#markup' => '<span id="text">Login In</span>
            <span id="key"><i class="fas fa-key"></i></span>'
);

$form['register'] = array(
'#type' => 'item',
'#title' => t(''),
'#markup' => '<div>Register</div>'
);

$form['tellmemore'] = array(
'#type' => 'item',
'#title' => t(''),
'#markup' => '<div>Tell me more</div>'
);

$form['help'] = array(
'#type' => 'item',
'#title' => t(''),
'#markup' => '<div>Help using the site</div>'
);

return $form;

}

function regpanel_theme($existing, $type, $theme, $path) {

    $items['regpanel_form'] = array(
    'render element' => 'form',
    'template' => 'regpanel',
    'path' => drupal_get_path("module", "regpanel"). '/template/form',

    );

    return $items;


}

	
	


